// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/echo.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 输出消息
type Echo struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Echo) Reset()         { *m = Echo{} }
func (m *Echo) String() string { return proto.CompactTextString(m) }
func (*Echo) ProtoMessage()    {}
func (*Echo) Descriptor() ([]byte, []int) {
	return fileDescriptor_91d721030cfcf875, []int{0}
}

func (m *Echo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Echo.Unmarshal(m, b)
}
func (m *Echo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Echo.Marshal(b, m, deterministic)
}
func (m *Echo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Echo.Merge(m, src)
}
func (m *Echo) XXX_Size() int {
	return xxx_messageInfo_Echo.Size(m)
}
func (m *Echo) XXX_DiscardUnknown() {
	xxx_messageInfo_Echo.DiscardUnknown(m)
}

var xxx_messageInfo_Echo proto.InternalMessageInfo

func (m *Echo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Echo)(nil), "grpc_demo_go.protobuf.message.Echo")
}

func init() { proto.RegisterFile("message/echo.proto", fileDescriptor_91d721030cfcf875) }

var fileDescriptor_91d721030cfcf875 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x4f, 0x4d, 0xce, 0xc8, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92,
	0x4d, 0x2f, 0x2a, 0x48, 0x8e, 0x4f, 0x49, 0xcd, 0xcd, 0x8f, 0x4f, 0x87, 0x8a, 0x25, 0x95, 0xa6,
	0xe9, 0x41, 0x55, 0x2a, 0x29, 0x70, 0xb1, 0xb8, 0x26, 0x67, 0xe4, 0x0b, 0x49, 0x70, 0xb1, 0x43,
	0x85, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x27, 0x2b, 0x27, 0x6e, 0x90, 0x0a,
	0x5f, 0x08, 0x37, 0x0a, 0x6c, 0x9e, 0x2e, 0xc8, 0x3c, 0xdd, 0xf4, 0x7c, 0x7d, 0x98, 0x79, 0xfa,
	0x50, 0xd5, 0x8b, 0x98, 0x90, 0x15, 0x27, 0xb1, 0x81, 0xe5, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x85, 0x54, 0x37, 0xf6, 0x99, 0x00, 0x00, 0x00,
}
